name: Notify of issues resolved in latest Doer Cloud deploy

on:
  push:
    branches:
      - doer-cloud-current
  workflow_dispatch:
    inputs:
      before:
        description: "Old commit-ish"
        required: true
      after:
        description: "New commit-ish"
        required: true
      stream:
        description: "Stream to send to"
        default: "doer cloud"
      topic:
        description: "Topic to send to"
        default: "latest deploy"

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  build-messages:
    runs-on: ubuntu-latest
    outputs:
      filenames: ${{ steps.set-matrix.outputs.filenames }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install uv
        run: |
          ./scripts/lib/install-uv

      - name: Generate list of resolved issues
        id: generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE: ${{ inputs.before || github.event.before }}
          HEAD: ${{ inputs.after || github.event.after }}
        run: |
          set -o pipefail

          mkdir closed-by-commits-output
          ./tools/closed-by-commits "$BASE" "$HEAD" \
            | perl -ple 'undef $/;s/\n\n/\x00/g' \
            | split -t '\0' -C 8000 -d - closed-by-commits-output/message-
          perl -pi -e 's/\00/\n\n/g' closed-by-commits-output/message-*

      - name: Upload messages as artifacts
        uses: actions/upload-artifact@v5
        with:
          name: closed-by-commits-output
          path: closed-by-commits-output/

      - name: Store filename list for matrix
        id: set-matrix
        run: |
          cd closed-by-commits-output/
          echo "filenames=$(ls | jq -Rnc '[inputs]')" >> $GITHUB_OUTPUT

  send-messages:
    needs: build-messages
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        filename: ${{ fromJson(needs.build-messages.outputs.filenames) }}
    if: ${{ success() && github.repository == 'doer/doer' }}
    steps:
      - name: Download messages as artifacts
        uses: actions/download-artifact@v6
        with:
          name: closed-by-commits-output
          path: closed-by-commits-output/

      - name: Read message contents
        id: read-file
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat "closed-by-commits-output/$FILENAME" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          FILENAME: ${{ matrix.filename }}

      - name: Send to Doer
        uses: doer/github-actions-doer/send-message@v1
        with:
          api-key: ${{ secrets.DOER_BOT_KEY }}
          email: "github-actions-bot@chat.zulip.org"
          organization-url: "https://chat.zulip.org"
          to: "${{ inputs.stream || 'doer cloud' }}"
          topic: "${{ inputs.topic || 'latest deploy' }}"
          type: "stream"
          content: ${{ steps.read-file.outputs.content }}
